### ISSUE TITLE
How to prove if quality actually switched?

### ISSUE THREAD

**Issue by tomByrer** [PonyFrance/videojs-resolution-switcher#3]
I made a demo: https://codepen.io/tomByrer/pen/vbyNJq
But I am not sure if the quality is actually switching?  Video.JS's GUI changed between 144, 480, 720, etc, but I do not know how to prove if YouTube is actually changing the qualtiy?

**Comment by mkody** [comment]
You can right click on the video and access the "Stats for Nerds" from the embeded Youtube Player.  
I never tried to embed Youtube with VideoJS (I think it's pointless...) so it might actually not work at all.

**Comment by tomByrer** [comment]
Thanks for the tip!
![youtube-stats-for-nerds](https://user-images.githubusercontent.com/1308419/52062394-0db5f100-2536-11e9-90ea-0440b274d4d9.JPG)
I guess it means x480?
If that is the case, then it seems the resolution does not change when I use this plugin.  Neither the stats nor the visual resolution changes when I change this plugin's menu.

I see your point about "Youtube with VideoJS is pointless" since YT has a built-in good player.  But I want to make a VideoJS plugin and not create a second one for YT's player.

**Comment by mkody** [comment]
Yep, it looks like it stays at "auto".
I see right when I open my console that the YouTube JS API is throwing an error (even without the plugin).

Trying to force a resolution manually using VideoJS' `setPlaybackQuality()` for the YouTube tech doesn't do anything either. It might be that something broke within VideoJS itself.
